# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRO-eYbtTwwItepVJz5SL_g10JH3Se95
"""

!pip install streamlit pyngrok -q
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

st.set_page_config(page_title="Crypto Analysis Pro", layout="wide")
st.title("🚀 Crypto Data Engineering & Prediction")

try:
    df = pd.read_csv('crypto_data.csv')
except:
    st.error("CSV file nahi mili! Dummy data use ho raha hai.")
    data = {
        'Coin': ['BTC', 'BTC', 'BTC', 'ETH', 'ETH', 'ETH'],
        'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-01', '2024-01-02', '2024-01-03'],
        'Price': [42000, 43000, 42500, 2200, 2300, 2400],
        'Volume': [100, 150, 120, 500, 600, 550]
    }
    df = pd.DataFrame(data)

df['Coin'] = df['Coin'].replace({'Bitcoin': 'BTC'})
df['Date'] = pd.to_datetime(df['Date'])

selected_coin = st.sidebar.selectbox("Select Coin for Prediction", df['Coin'].unique())
df_filtered = df[df['Coin'] == selected_coin].copy()

st.header(f"📊 Market Insights: {selected_coin}")
co11, co12 = st.columns(2)

with co11:
    fig1, ax1 = plt.subplots()
    ax1.bar(df['Coin'].unique(), df.groupby('Coin')['Price'].mean(), color='skyblue')
    ax1.set_title("Average Price Comparision")
    st.pyplot(fig1)
    plt.close()

with co12:
    volume_data = df.groupby('Coin')['Volume'].sum()
    fig2, ax2 = plt.subplots()
    ax2.pie(volume_data, labels=volume_data.index, autopct='%1.1f%%')
    st.pyplot(fig2)
    plt.close()

st.header(f"📈 Price Trend: {selected_coin} Future Prediction")

df_filtered['Day_Index'] = np.arange(len(df_filtered))
X = df_filtered[['Day_Index']] # Feature DataFrame
y = df_filtered['Price']

model = LinearRegression()
model.fit(X, y)

next_day = pd.DataFrame([[len(df_filtered)]], columns = ['Day_Index'])
prediction = model.predict(next_day)[0]
current_price = df_filtered['Price'].iloc[-1]

fig3, ax3 = plt.subplots(figsize=(10,4))
ax3.plot(df_filtered['Day_Index'], df_filtered['Price'], label="Past Prices", marker='o')
ax3.scatter([len(df_filtered)], [prediction], color='red', marker='*', s=200, label="Prediction")
ax3.legend()
st.pyplot(fig3)
plt.close()

if prediction > current_price:
    st.success(f"✅ BULLISH: Predicted ${prediction:.2f}")
else:
    st.warning(f"⚠️ BEARISH: Predicted ${prediction:.2f}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.linear_model import LinearRegression
# import numpy as np
# 
# st.set_page_config(page_title="Crypto Analysis Pro", layout="wide")
# st.title("🚀 Crypto Data Engineering & Prediction")
# 
# try:
#     df = pd.read_csv('crypto_data.csv')
# except:
#     st.error("CSV file nahi mili! Dummy data use ho raha hai.")
#     data = {
#         'Coin': ['BTC', 'BTC', 'BTC', 'ETH', 'ETH', 'ETH'],
#         'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-01', '2024-01-02', '2024-01-03'],
#         'Price': [42000, 43000, 42500, 2200, 2300, 2400],
#         'Volume': [100, 150, 120, 500, 600, 550]
#     }
#     df = pd.DataFrame(data)
# 
# df['Coin'] = df['Coin'].replace({'Bitcoin': 'BTC'})
# df['Date'] = pd.to_datetime(df['Date'])
# 
# selected_coin = st.sidebar.selectbox("Select Coin for Prediction", df['Coin'].unique())
# df_filtered = df[df['Coin'] == selected_coin].copy()
# 
# st.header(f"📊 Market Insights: {selected_coin}")
# co11, co12 = st.columns(2)
# 
# with co11:
#     fig1, ax1 = plt.subplots()
#     ax1.bar(df['Coin'].unique(), df.groupby('Coin')['Price'].mean(), color='skyblue')
#     ax1.set_title("Average Price Comparision")
#     st.pyplot(fig1)
#     plt.close()
# 
# with co12:
#     volume_data = df.groupby('Coin')['Volume'].sum()
#     fig2, ax2 = plt.subplots()
#     ax2.pie(volume_data, labels=volume_data.index, autopct='%1.1f%%')
#     st.pyplot(fig2)
#     plt.close()
# 
# st.header(f"📈 Price Trend: {selected_coin} Future Prediction")
# 
# df_filtered['Day_Index'] = np.arange(len(df_filtered))
# X = df_filtered[['Day_Index']] # Feature DataFrame
# y = df_filtered['Price']
# 
# model = LinearRegression()
# model.fit(X, y)
# 
# next_day = pd.DataFrame([[len(df_filtered)]], columns = ['Day_Index'])
# prediction = model.predict(next_day)[0]
# current_price = df_filtered['Price'].iloc[-1]
# 
# fig3, ax3 = plt.subplots(figsize=(10,4))
# ax3.plot(df_filtered['Day_Index'], df_filtered['Price'], label="Past Prices", marker='o')
# ax3.scatter([len(df_filtered)], [prediction], color='red', marker='*', s=200, label="Prediction")
# ax3.legend()
# st.pyplot(fig3)
# plt.close()
# 
# if prediction > current_price:
#     st.success(f"✅ BULLISH: Predicted ${prediction:.2f}")
# else:
#     st.warning(f"⚠️ BEARISH: Predicted ${prediction:.2f}")

